import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          打造基于 GPT-3 的搜索引擎
        </h1>

        <h1 className={styles.title}>
          无需注册体验: <a href="https://chat.bygpt.com">Chat By GPT</a>
        </h1>

        <p className={styles.description}>
          敬请期待{' '}
          <code className={styles.code}>By GPT</code>
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            GPT api 强力驱动
          </span>
        </a>
      </footer>
    </div>
  )
}
